services:
  database:
    image: postgres:14-bullseye
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  server:
    build:
      context: .
      dockerfile: environment/Dockerfile
    volumes:
      - "./:/home"

  loadbalancer:
    image: nginx
    ports: 
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
