services:
  database:
    image: postgres:14-bullseye
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  server:
    build:
      context: .
      dockerfile: environment/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "./aplicacao:/home"
